# Generated by Django 4.0.2 on 2022-05-14 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabangbank',
            fields=[
                ('kode', models.AutoField(primary_key=True, serialize=False)),
                ('nama_cabang', models.CharField(max_length=50)),
                ('alamat_cabang', models.TextField()),
            ],
            options={
                'db_table': 'cabang',
            },
        ),
        migrations.CreateModel(
            name='Nasabah',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=45)),
                ('tempat_lahir', models.CharField(max_length=45)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('laki-laki', 'Laki-Laki'), ('perempuan', 'Perempuan')], default=None, max_length=10)),
                ('alamat', models.TextField()),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'nasabah',
            },
        ),
        migrations.CreateModel(
            name='Rekening',
            fields=[
                ('no_rekening', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('saldo', models.IntegerField()),
                ('id_nasabah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_abc_rekening_bank_abc_nasabah', to='bank_abc.nasabah')),
                ('kode_cabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_abc_cabangbank', to='bank_abc.cabangbank')),
            ],
            options={
                'db_table': 'rekening',
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('no_transaksi', models.AutoField(primary_key=True, serialize=False)),
                ('tujuan', models.IntegerField()),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('jumlah', models.IntegerField()),
                ('id_nasabah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_abc_nasabah', to='bank_abc.nasabah')),
                ('no_rekening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_abc_rekening', to='bank_abc.rekening')),
            ],
            options={
                'db_table': 'transaksi',
            },
        ),
    ]
